services:
  todo-app:
    build: .
    command: ./wait-for-postgres.sh db ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_PASSWORD: qwerty

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: todo
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data

